//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetierRvMedical2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personne", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical2.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetierRvMedical2.ServiceReference1.Patient))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetierRvMedical2.ServiceReference1.Utilisateur))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetierRvMedical2.ServiceReference1.Medecin))]
    public partial class Personne : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddresseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateNaissanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addresse {
            get {
                return this.AddresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AddresseField, value) != true)) {
                    this.AddresseField = value;
                    this.RaisePropertyChanged("Addresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateNaissance {
            get {
                return this.DateNaissanceField;
            }
            set {
                if ((this.DateNaissanceField.Equals(value) != true)) {
                    this.DateNaissanceField = value;
                    this.RaisePropertyChanged("DateNaissance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdP {
            get {
                return this.IdPField;
            }
            set {
                if ((this.IdPField.Equals(value) != true)) {
                    this.IdPField = value;
                    this.RaisePropertyChanged("IdP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPrenom {
            get {
                return this.NomPrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPrenomField, value) != true)) {
                    this.NomPrenomField = value;
                    this.RaisePropertyChanged("NomPrenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical2.Models")]
    [System.SerializableAttribute()]
    public partial class Patient : MetierRvMedical2.ServiceReference1.Personne {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupeSanguinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> PoidsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> TailleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupeSanguin {
            get {
                return this.GroupeSanguinField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupeSanguinField, value) != true)) {
                    this.GroupeSanguinField = value;
                    this.RaisePropertyChanged("GroupeSanguin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Poids {
            get {
                return this.PoidsField;
            }
            set {
                if ((this.PoidsField.Equals(value) != true)) {
                    this.PoidsField = value;
                    this.RaisePropertyChanged("Poids");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Taille {
            get {
                return this.TailleField;
            }
            set {
                if ((this.TailleField.Equals(value) != true)) {
                    this.TailleField = value;
                    this.RaisePropertyChanged("Taille");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utilisateur", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical2.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MetierRvMedical2.ServiceReference1.Medecin))]
    public partial class Utilisateur : MetierRvMedical2.ServiceReference1.Personne {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifiantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotDePasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PremiereConnexionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetierRvMedical2.ServiceReference1.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRole {
            get {
                return this.IdRoleField;
            }
            set {
                if ((this.IdRoleField.Equals(value) != true)) {
                    this.IdRoleField = value;
                    this.RaisePropertyChanged("IdRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifiant {
            get {
                return this.IdentifiantField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifiantField, value) != true)) {
                    this.IdentifiantField = value;
                    this.RaisePropertyChanged("Identifiant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotDePasse {
            get {
                return this.MotDePasseField;
            }
            set {
                if ((object.ReferenceEquals(this.MotDePasseField, value) != true)) {
                    this.MotDePasseField = value;
                    this.RaisePropertyChanged("MotDePasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PremiereConnexion {
            get {
                return this.PremiereConnexionField;
            }
            set {
                if ((this.PremiereConnexionField.Equals(value) != true)) {
                    this.PremiereConnexionField = value;
                    this.RaisePropertyChanged("PremiereConnexion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetierRvMedical2.ServiceReference1.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Medecin", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical2.Models")]
    [System.SerializableAttribute()]
    public partial class Medecin : MetierRvMedical2.ServiceReference1.Utilisateur {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdSpecialiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroOrdreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetierRvMedical2.ServiceReference1.Specialite SpecialiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetierRvMedical2.ServiceReference1.Agenda[] agendaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdSpecialite {
            get {
                return this.IdSpecialiteField;
            }
            set {
                if ((this.IdSpecialiteField.Equals(value) != true)) {
                    this.IdSpecialiteField = value;
                    this.RaisePropertyChanged("IdSpecialite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroOrdre {
            get {
                return this.NumeroOrdreField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroOrdreField, value) != true)) {
                    this.NumeroOrdreField = value;
                    this.RaisePropertyChanged("NumeroOrdre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetierRvMedical2.ServiceReference1.Specialite Specialite {
            get {
                return this.SpecialiteField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialiteField, value) != true)) {
                    this.SpecialiteField = value;
                    this.RaisePropertyChanged("Specialite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetierRvMedical2.ServiceReference1.Agenda[] agenda {
            get {
                return this.agendaField;
            }
            set {
                if ((object.ReferenceEquals(this.agendaField, value) != true)) {
                    this.agendaField = value;
                    this.RaisePropertyChanged("agenda");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical2.Models")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleRoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeRole {
            get {
                return this.CodeRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeRoleField, value) != true)) {
                    this.CodeRoleField = value;
                    this.RaisePropertyChanged("CodeRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRole {
            get {
                return this.IdRoleField;
            }
            set {
                if ((this.IdRoleField.Equals(value) != true)) {
                    this.IdRoleField = value;
                    this.RaisePropertyChanged("IdRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LibelleRole {
            get {
                return this.LibelleRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleRoleField, value) != true)) {
                    this.LibelleRoleField = value;
                    this.RaisePropertyChanged("LibelleRole");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Specialite", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical2.Models")]
    [System.SerializableAttribute()]
    public partial class Specialite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeSpecialteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomSpecialteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeSpecialte {
            get {
                return this.CodeSpecialteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeSpecialteField, value) != true)) {
                    this.CodeSpecialteField = value;
                    this.RaisePropertyChanged("CodeSpecialte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomSpecialte {
            get {
                return this.NomSpecialteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomSpecialteField, value) != true)) {
                    this.NomSpecialteField = value;
                    this.RaisePropertyChanged("NomSpecialte");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agenda", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical2.Models")]
    [System.SerializableAttribute()]
    public partial class Agenda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreneauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataPlanifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeureDebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeureFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAgendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdMedecinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetierRvMedical2.ServiceReference1.Medecin MedecinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetierRvMedical2.ServiceReference1.RendezVous[] rendezVousField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Creneau {
            get {
                return this.CreneauField;
            }
            set {
                if ((this.CreneauField.Equals(value) != true)) {
                    this.CreneauField = value;
                    this.RaisePropertyChanged("Creneau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataPlanifier {
            get {
                return this.DataPlanifierField;
            }
            set {
                if ((this.DataPlanifierField.Equals(value) != true)) {
                    this.DataPlanifierField = value;
                    this.RaisePropertyChanged("DataPlanifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeureDebut {
            get {
                return this.HeureDebutField;
            }
            set {
                if ((object.ReferenceEquals(this.HeureDebutField, value) != true)) {
                    this.HeureDebutField = value;
                    this.RaisePropertyChanged("HeureDebut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeureFin {
            get {
                return this.HeureFinField;
            }
            set {
                if ((object.ReferenceEquals(this.HeureFinField, value) != true)) {
                    this.HeureFinField = value;
                    this.RaisePropertyChanged("HeureFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAgenda {
            get {
                return this.IdAgendaField;
            }
            set {
                if ((this.IdAgendaField.Equals(value) != true)) {
                    this.IdAgendaField = value;
                    this.RaisePropertyChanged("IdAgenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMedecin {
            get {
                return this.IdMedecinField;
            }
            set {
                if ((this.IdMedecinField.Equals(value) != true)) {
                    this.IdMedecinField = value;
                    this.RaisePropertyChanged("IdMedecin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lieu {
            get {
                return this.LieuField;
            }
            set {
                if ((object.ReferenceEquals(this.LieuField, value) != true)) {
                    this.LieuField = value;
                    this.RaisePropertyChanged("Lieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetierRvMedical2.ServiceReference1.Medecin Medecin {
            get {
                return this.MedecinField;
            }
            set {
                if ((object.ReferenceEquals(this.MedecinField, value) != true)) {
                    this.MedecinField = value;
                    this.RaisePropertyChanged("Medecin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Statut {
            get {
                return this.StatutField;
            }
            set {
                if ((object.ReferenceEquals(this.StatutField, value) != true)) {
                    this.StatutField = value;
                    this.RaisePropertyChanged("Statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetierRvMedical2.ServiceReference1.RendezVous[] rendezVous {
            get {
                return this.rendezVousField;
            }
            set {
                if ((object.ReferenceEquals(this.rendezVousField, value) != true)) {
                    this.rendezVousField = value;
                    this.RaisePropertyChanged("rendezVous");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RendezVous", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical2.Models")]
    [System.SerializableAttribute()]
    public partial class RendezVous : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetierRvMedical2.ServiceReference1.Agenda AgendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeRdvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateRvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeureRvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdAgendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdMedecinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdPatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRendezVousField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdSoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetierRvMedical2.ServiceReference1.Medecin MedecinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetierRvMedical2.ServiceReference1.Patient PatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MetierRvMedical2.ServiceReference1.Soin SoinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetierRvMedical2.ServiceReference1.Agenda Agenda {
            get {
                return this.AgendaField;
            }
            set {
                if ((object.ReferenceEquals(this.AgendaField, value) != true)) {
                    this.AgendaField = value;
                    this.RaisePropertyChanged("Agenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeRdv {
            get {
                return this.CodeRdvField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeRdvField, value) != true)) {
                    this.CodeRdvField = value;
                    this.RaisePropertyChanged("CodeRdv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateRv {
            get {
                return this.DateRvField;
            }
            set {
                if ((object.ReferenceEquals(this.DateRvField, value) != true)) {
                    this.DateRvField = value;
                    this.RaisePropertyChanged("DateRv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeureRv {
            get {
                return this.HeureRvField;
            }
            set {
                if ((object.ReferenceEquals(this.HeureRvField, value) != true)) {
                    this.HeureRvField = value;
                    this.RaisePropertyChanged("HeureRv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdAgenda {
            get {
                return this.IdAgendaField;
            }
            set {
                if ((this.IdAgendaField.Equals(value) != true)) {
                    this.IdAgendaField = value;
                    this.RaisePropertyChanged("IdAgenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMedecin {
            get {
                return this.IdMedecinField;
            }
            set {
                if ((this.IdMedecinField.Equals(value) != true)) {
                    this.IdMedecinField = value;
                    this.RaisePropertyChanged("IdMedecin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPatient {
            get {
                return this.IdPatientField;
            }
            set {
                if ((this.IdPatientField.Equals(value) != true)) {
                    this.IdPatientField = value;
                    this.RaisePropertyChanged("IdPatient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRendezVous {
            get {
                return this.IdRendezVousField;
            }
            set {
                if ((this.IdRendezVousField.Equals(value) != true)) {
                    this.IdRendezVousField = value;
                    this.RaisePropertyChanged("IdRendezVous");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdSoin {
            get {
                return this.IdSoinField;
            }
            set {
                if ((this.IdSoinField.Equals(value) != true)) {
                    this.IdSoinField = value;
                    this.RaisePropertyChanged("IdSoin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetierRvMedical2.ServiceReference1.Medecin Medecin {
            get {
                return this.MedecinField;
            }
            set {
                if ((object.ReferenceEquals(this.MedecinField, value) != true)) {
                    this.MedecinField = value;
                    this.RaisePropertyChanged("Medecin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetierRvMedical2.ServiceReference1.Patient Patient {
            get {
                return this.PatientField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientField, value) != true)) {
                    this.PatientField = value;
                    this.RaisePropertyChanged("Patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MetierRvMedical2.ServiceReference1.Soin Soin {
            get {
                return this.SoinField;
            }
            set {
                if ((object.ReferenceEquals(this.SoinField, value) != true)) {
                    this.SoinField = value;
                    this.RaisePropertyChanged("Soin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Soin", Namespace="http://schemas.datacontract.org/2004/07/MetierRvMedical2.Models")]
    [System.SerializableAttribute()]
    public partial class Soin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeSoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoutSoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSoinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomSoinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeSoin {
            get {
                return this.CodeSoinField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeSoinField, value) != true)) {
                    this.CodeSoinField = value;
                    this.RaisePropertyChanged("CodeSoin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoutSoin {
            get {
                return this.CoutSoinField;
            }
            set {
                if ((this.CoutSoinField.Equals(value) != true)) {
                    this.CoutSoinField = value;
                    this.RaisePropertyChanged("CoutSoin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSoin {
            get {
                return this.IdSoinField;
            }
            set {
                if ((this.IdSoinField.Equals(value) != true)) {
                    this.IdSoinField = value;
                    this.RaisePropertyChanged("IdSoin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomSoin {
            get {
                return this.NomSoinField;
            }
            set {
                if ((object.ReferenceEquals(this.NomSoinField, value) != true)) {
                    this.NomSoinField = value;
                    this.RaisePropertyChanged("NomSoin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMedecinService")]
    public interface IMedecinService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedecinService/DoWork", ReplyAction="http://tempuri.org/IMedecinService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedecinService/DoWork", ReplyAction="http://tempuri.org/IMedecinService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedecinService/GetMedecinByNumeroOrdre", ReplyAction="http://tempuri.org/IMedecinService/GetMedecinByNumeroOrdreResponse")]
        MetierRvMedical2.ServiceReference1.Medecin GetMedecinByNumeroOrdre(string numeroOrdre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedecinService/GetMedecinByNumeroOrdre", ReplyAction="http://tempuri.org/IMedecinService/GetMedecinByNumeroOrdreResponse")]
        System.Threading.Tasks.Task<MetierRvMedical2.ServiceReference1.Medecin> GetMedecinByNumeroOrdreAsync(string numeroOrdre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedecinService/ActiverMedecin", ReplyAction="http://tempuri.org/IMedecinService/ActiverMedecinResponse")]
        void ActiverMedecin(string numeroOrdre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedecinService/ActiverMedecin", ReplyAction="http://tempuri.org/IMedecinService/ActiverMedecinResponse")]
        System.Threading.Tasks.Task ActiverMedecinAsync(string numeroOrdre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedecinService/DesactiverMedecin", ReplyAction="http://tempuri.org/IMedecinService/DesactiverMedecinResponse")]
        void DesactiverMedecin(string numeroOrdre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedecinService/DesactiverMedecin", ReplyAction="http://tempuri.org/IMedecinService/DesactiverMedecinResponse")]
        System.Threading.Tasks.Task DesactiverMedecinAsync(string numeroOrdre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMedecinServiceChannel : MetierRvMedical2.ServiceReference1.IMedecinService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MedecinServiceClient : System.ServiceModel.ClientBase<MetierRvMedical2.ServiceReference1.IMedecinService>, MetierRvMedical2.ServiceReference1.IMedecinService {
        
        public MedecinServiceClient() {
        }
        
        public MedecinServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MedecinServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedecinServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedecinServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public MetierRvMedical2.ServiceReference1.Medecin GetMedecinByNumeroOrdre(string numeroOrdre) {
            return base.Channel.GetMedecinByNumeroOrdre(numeroOrdre);
        }
        
        public System.Threading.Tasks.Task<MetierRvMedical2.ServiceReference1.Medecin> GetMedecinByNumeroOrdreAsync(string numeroOrdre) {
            return base.Channel.GetMedecinByNumeroOrdreAsync(numeroOrdre);
        }
        
        public void ActiverMedecin(string numeroOrdre) {
            base.Channel.ActiverMedecin(numeroOrdre);
        }
        
        public System.Threading.Tasks.Task ActiverMedecinAsync(string numeroOrdre) {
            return base.Channel.ActiverMedecinAsync(numeroOrdre);
        }
        
        public void DesactiverMedecin(string numeroOrdre) {
            base.Channel.DesactiverMedecin(numeroOrdre);
        }
        
        public System.Threading.Tasks.Task DesactiverMedecinAsync(string numeroOrdre) {
            return base.Channel.DesactiverMedecinAsync(numeroOrdre);
        }
    }
}
